<?php

namespace Database\Seeders;

use App\Models\EmailInbox;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EmailInboxSeeder extends Seeder
{
    public function run(): void
    {
        $emails = [
            [
                'message_id'      => 'MSG-2026-001@gmail.com',
                'from_name'       => 'Marie Dupont',
                'from_email'      => 'marie.dupont@gmail.com',
                'subject'         => 'Colis non reçu - Commande #FR2026-458921',
                'body_text'       => "Bonjour,\n\nJe me permets de vous contacter car je n'ai toujours pas reçu mon colis commandé il y a 8 jours. Le numéro de suivi FR2026-458921 indique \"En cours de livraison\" depuis 3 jours sans évolution.\n\nJ'attends ce colis de toute urgence car il contient des médicaments importants pour ma mère âgée.\n\nPouvez-vous intervenir rapidement ?\n\nCordialement,\nMarie Dupont\nTél : 06 12 34 56 78",
                'received_at'     => Carbon::now()->subHours(2),
                'is_read'         => false,
                'is_processed'    => false,
                'status'          => 'unread',
                'ai_service_type' => 'suivi_colis',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-002@gmail.com',
                'from_name'       => 'Jean-Pierre Martin',
                'from_email'      => 'jp.martin.pro@orange.fr',
                'subject'         => 'Réclamation - Erreur de facturation sur mon compte La Banque Postale',
                'body_text'       => "Madame, Monsieur,\n\nJe constate avec stupéfaction que mon compte courant a été débité deux fois du montant de 247,50€ le 3 mai 2026 pour la même opération de virement.\n\nCela me cause de sérieux problèmes car j'ai des prélèvements automatiques qui risquent d'être rejetés.\n\nJ'exige le remboursement immédiat du doublon et des excuses formelles.\n\nJean-Pierre Martin\nNuméro client : LBP-789456123",
                'received_at'     => Carbon::now()->subHours(5),
                'is_read'         => true,
                'is_processed'    => false,
                'status'          => 'read',
                'ai_service_type' => 'reclamation',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-003@gmail.com',
                'from_name'       => 'Sophie Leblanc',
                'from_email'      => 'sophie.leblanc@hotmail.fr',
                'subject'         => "Demande d'information - Offre Colissimo International",
                'body_text'       => "Bonjour,\n\nJe suis responsable des achats d'une PME et nous souhaitons développer notre activité e-commerce vers l'Espagne, l'Italie et l'Allemagne.\n\nPourriez-vous m'informer sur :\n- Les tarifs Colissimo International pour des colis de 2 à 5 kg\n- Les délais de livraison garantis\n- Les options de suivi disponibles\n- Les conditions pour un contrat entreprise\n\nNous envoyons environ 200 colis par mois.\n\nMerci d'avance,\nSophie Leblanc - Directrice Achats\nTech Solutions SAS - SIRET 123 456 789 00012",
                'received_at'     => Carbon::now()->subHours(8),
                'is_read'         => false,
                'is_processed'    => false,
                'status'          => 'unread',
                'ai_service_type' => 'info_offre',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-004@gmail.com',
                'from_name'       => 'Ahmed Benali',
                'from_email'      => 'ahmed.benali85@yahoo.fr',
                'subject'         => 'URGENT - Colis perdu contenant documents officiels',
                'body_text'       => "Bonjour,\n\nC'est une situation URGENTE. J'ai envoyé par Chronopost mon dossier de demande de titre de séjour (documents originaux irremplaçables) le 28 avril. Le numéro de suivi est CP826549183FR.\n\nLe suivi indique \"Incident de livraison\" depuis le 30 avril et personne ne me rappelle malgré mes 4 appels au service client.\n\nSans ces documents, mon rendez-vous en préfecture du 15 mai est compromis. Je risque de perdre mon travail.\n\nJ'ai besoin d'une réponse AUJOURD'HUI.\n\nAhmed Benali",
                'received_at'     => Carbon::now()->subHours(1),
                'is_read'         => false,
                'is_processed'    => false,
                'status'          => 'unread',
                'ai_service_type' => 'escalade_mediateur',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-005@gmail.com',
                'from_name'       => 'Isabelle Rousseau',
                'from_email'      => 'i.rousseau.handicap@gmail.com',
                'subject'         => 'Accessibilité - Retrait impossible en bureau de poste',
                'body_text'       => "Bonjour,\n\nJe suis titulaire d'une RQTH et utilisatrice de fauteuil roulant. Le bureau de poste de mon quartier (75012 Paris, rue de Reuilly) n'est pas accessible : pas de rampe d'accès, guichet trop haut.\n\nOn m'a refusé la livraison à domicile pour mon recommandé alors que c'est prévu par la loi pour les personnes en situation de handicap.\n\nJe souhaite porter réclamation formelle et obtenir une solution pérenne.\n\nIsabelle Rousseau\nNuméro RQTH : MDPH75-2024-8834",
                'received_at'     => Carbon::now()->subDay(),
                'is_read'         => true,
                'is_processed'    => true,
                'status'          => 'processing',
                'ai_service_type' => 'handicap',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-006@gmail.com',
                'from_name'       => 'Thomas Bernard',
                'from_email'      => 'thomas.bernard.compta@gmail.com',
                'subject'         => "Changement d'adresse - Redirection de courrier",
                'body_text'       => "Bonjour,\n\nNous déménageons notre siège social le 20 mai 2026. Pourriez-vous mettre en place une redirection de courrier professionnelle ?\n\nAncienne adresse : 45 rue du Commerce, 69001 Lyon\nNouvelle adresse : 12 avenue de la République, 69003 Lyon\n\nDurée souhaitée : 12 mois\nNombre de destinataires : 3\n\nThomas Bernard - Gérant, Bernard & Associés SARL",
                'received_at'     => Carbon::now()->subDays(2),
                'is_read'         => true,
                'is_processed'    => true,
                'status'          => 'resolved',
                'ai_service_type' => 'info_offre',
                'ai_response'     => "Bonjour Monsieur Bernard,\n\nNous avons bien pris note de votre demande de redirection de courrier professionnel...\n\nCordialement,\nLe Service Client La Poste",
                'validated_response' => "Bonjour Monsieur Bernard,\n\nNous avons bien pris note de votre demande de redirection de courrier professionnel pour votre déménagement du 20 mai 2026.\n\nLe service de réexpédition définitive pour entreprise est disponible à partir de 89€/an pour 3 destinataires. La mise en place nécessite 5 jours ouvrés.\n\nCordialement,\nSophie M. - Conseillère Clientèle La Poste",
                'validated_at'    => Carbon::now()->subDays(1),
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-007@gmail.com',
                'from_name'       => 'Nathalie Petit',
                'from_email'      => 'nathalie.petit@sfr.fr',
                'subject'         => 'Remboursement colis endommagé - Dossier #REC-2026-7823',
                'body_text'       => "Bonjour,\n\nSuite à notre échange téléphonique du 2 mai, je transmets les photos du colis endommagé reçu le 29 avril.\n\nLe contenu (service de vaisselle en porcelaine, valeur 320€) est entièrement brisé. J'avais souscrit l'assurance Valeur Déclarée à 350€. Quand puis-je espérer le remboursement ?\n\nNathalie Petit\nDossier : REC-2026-7823",
                'received_at'     => Carbon::now()->subDays(3),
                'is_read'         => true,
                'is_processed'    => false,
                'status'          => 'read',
                'ai_service_type' => 'reclamation',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-008@gmail.com',
                'from_name'       => 'Karim Mansour',
                'from_email'      => 'karim.mansour.import@gmail.com',
                'subject'         => 'Dédouanement colis depuis le Maroc - Frais incompréhensibles',
                'body_text'       => "Bonjour,\n\nJ'ai reçu un avis de passage pour un colis en provenance du Maroc. On me demande de payer 87€ de frais de douane pour un colis de vêtements et épices d'une valeur déclarée de 150€.\n\nCes frais semblent excessifs. Y a-t-il une erreur ? Comment contester ?\n\nKarim Mansour",
                'received_at'     => Carbon::now()->subHours(12),
                'is_read'         => false,
                'is_processed'    => false,
                'status'          => 'unread',
                'ai_service_type' => 'info_offre',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'FORM-2026-001',
                'from_name'       => 'Lucas Moreau',
                'from_email'      => 'lucas.moreau@gmail.com',
                'subject'         => '[Formulaire] Demande de rendez-vous - Ouverture compte professionnel',
                'body_text'       => "Formulaire soumis le 7 mai 2026\n\nNom : Lucas Moreau\nEntreprise : Moreau Digital Agency\nSIRET : 987 654 321 00034\nTéléphone : 07 89 01 23 45\n\nDemande : Souhaite ouvrir un compte courant professionnel et un compte épargne entreprise. Disponible mardi ou jeudi après-midi.",
                'received_at'     => Carbon::now()->subHours(3),
                'is_read'         => false,
                'is_processed'    => false,
                'status'          => 'unread',
                'ai_service_type' => 'formulaire',
                'source'          => 'form',
            ],
            [
                'message_id'      => 'FORM-2026-002',
                'from_name'       => 'Amina Diallo',
                'from_email'      => 'amina.diallo@outlook.com',
                'subject'         => '[Formulaire] Signalement - Comportement inapproprié en agence',
                'body_text'       => "Formulaire soumis le 6 mai 2026\n\nNom : Amina Diallo\nAgence concernée : La Poste - 13 place de la Mairie, 93100 Montreuil\nDate de l'incident : 5 mai 2026 vers 14h30\n\nDescription : J'ai été traitée avec condescendance et ignorée au profit de clients arrivés après moi. Je souhaite un suivi formel de cette plainte.",
                'received_at'     => Carbon::now()->subDays(1),
                'is_read'         => true,
                'is_processed'    => false,
                'status'          => 'read',
                'ai_service_type' => 'reclamation',
                'source'          => 'form',
            ],
            [
                'message_id'      => 'MSG-2026-009@gmail.com',
                'from_name'       => 'Pierre Fontaine',
                'from_email'      => 'p.fontaine.retraite@gmail.com',
                'subject'         => 'Aide - Je ne comprends pas comment utiliser le suivi en ligne',
                'body_text'       => "Bonjour,\n\nJe suis retraité et je ne suis pas très à l'aise avec Internet. J'ai reçu un SMS avec un numéro de colis 6C26456789123 mais quand j'essaie sur le site, ça ne marche pas.\n\nEst-ce que quelqu'un peut m'appeler ? Mon numéro est le 04 78 23 45 67.\n\nMerci,\nPierre Fontaine",
                'received_at'     => Carbon::now()->subHours(6),
                'is_read'         => false,
                'is_processed'    => false,
                'status'          => 'unread',
                'ai_service_type' => 'suivi_colis',
                'source'          => 'imap',
            ],
            [
                'message_id'      => 'MSG-2026-010@gmail.com',
                'from_name'       => 'Entreprise BioFresh',
                'from_email'      => 'logistique@biofresh.fr',
                'subject'         => 'Contrat Colissimo Pro - Renouvellement et augmentation volume',
                'body_text'       => "Bonjour,\n\nNotre contrat Colissimo Pro n°CP-2024-BF-8834 arrive à échéance le 31 mai 2026. Nous souhaitons le renouveler et augmenter nos volumes : de 500 à 1200 colis/mois.\n\nPouvez-vous nous proposer une nouvelle grille tarifaire ?\n\nDirection Logistique - BioFresh SAS",
                'received_at'     => Carbon::now()->subDays(4),
                'is_read'         => true,
                'is_processed'    => true,
                'status'          => 'archived',
                'ai_service_type' => 'info_offre',
                'archived_at'     => Carbon::now()->subDays(2),
                'source'          => 'imap',
            ],
        ];

        foreach ($emails as $email) {
            EmailInbox::updateOrCreate(['message_id' => $email['message_id']], $email);
        }

        $this->command->info('12 mails illustratifs créés avec succès.');
    }
}
